pull_request_rules:
  - name: Automatic merge on approval and CI success
    conditions:
      - base=main
      - label="Please Merge"
      - check-success=bundle-check-changed
      - check-success=go-test
      - "#review-requested=0"
    actions:
      merge:
        method: squash

  - name: Automatic merge Dependabot PRs (for actions) on CI success
    conditions:
      - base=main
      - author=dependabot[bot]
      - label="github_actions"
      - check-success=bundle-check-changed
      - check-success=go-test
      - "#review-requested=0"
    actions:
      merge:
        method: squash
