apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "lb.lbconfig.carlosedp.com/v1",
          "kind": "ExternalLoadBalancer",
          "metadata": {
            "name": "externalloadbalancer-infra-sample",
            "namespace": "lbconfig-operator-system"
          },
          "spec": {
            "backend": "backend-f5-sample",
            "monitor": {
              "monitortype": "http",
              "path": "/healthz",
              "port": 1936
            },
            "ports": [
              80,
              443
            ],
            "type": "infra",
            "vip": "192.168.1.45"
          }
        },
        {
          "apiVersion": "lb.lbconfig.carlosedp.com/v1",
          "kind": "ExternalLoadBalancer",
          "metadata": {
            "name": "externalloadbalancer-master-sample",
            "namespace": "lbconfig-operator-system"
          },
          "spec": {
            "backend": "backend-f5-sample",
            "monitor": {
              "monitortype": "https",
              "path": "/healthz",
              "port": 6443
            },
            "ports": [
              6443
            ],
            "type": "master",
            "vip": "192.168.1.40"
          }
        },
        {
          "apiVersion": "lb.lbconfig.carlosedp.com/v1",
          "kind": "LoadBalancerBackend",
          "metadata": {
            "name": "backend-f5-sample",
            "namespace": "lbconfig-operator-system"
          },
          "spec": {
            "provider": {
              "creds": "f5-creds",
              "host": "192.168.1.35",
              "partition": "Common",
              "port": 443,
              "validatecerts": false,
              "vendor": "F5"
            }
          }
        },
        {
          "apiVersion": "lb.lbconfig.carlosedp.com/v1",
          "kind": "LoadBalancerBackend",
          "metadata": {
            "name": "backend-netscaler-sample",
            "namespace": "lbconfig-operator-system"
          },
          "spec": {
            "provider": {
              "creds": "netscaler-creds",
              "host": "192.168.1.36",
              "port": 443,
              "validatecerts": false,
              "vendor": "netscaler"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: lbconfig-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ExternalLoadBalancer is the Schema for the externalloadbalancers
        API
      displayName: External Load Balancer
      kind: ExternalLoadBalancer
      name: externalloadbalancers.lb.lbconfig.carlosedp.com
      version: v1
    - description: LoadBalancerBackend is the Schema for the loadbalancerbackends
        API
      displayName: Load Balancer Backend
      kind: LoadBalancerBackend
      name: loadbalancerbackends.lb.lbconfig.carlosedp.com
      version: v1
  description: This operator manages external Load Balancer instances and creates
    VIPs and IP Pools with Monitors for the Master and Infra nodes based on it's roles
    and/or labels.
  displayName: External Load Balancer Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - lb.lbconfig.carlosedp.com
          resources:
          - externalloadbalancers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - lb.lbconfig.carlosedp.com
          resources:
          - externalloadbalancers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - lb.lbconfig.carlosedp.com
          resources:
          - loadbalancerbackends
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - lb.lbconfig.carlosedp.com
          resources:
          - loadbalancerbackends/status
          verbs:
          - get
          - list
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: lbconfig-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: lbconfig-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.12.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: carlosedp/lbconfig-operator:v0.1.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: lbconfig-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: lbconfig-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - loadbalancer
  - balancing
  - network
  links:
  - name: Lbconfig Operator
    url: https://lbconfig-operator.domain
  maintainers:
  - email: carlosedp@gmail.com
    name: CarlosEDP
  maturity: alpha
  provider:
    name: carlosedp.com
    url: https://github.com/carlosedp/lbconfig-operator
  version: 0.1.0
