# permissions for end users to view externalloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: externalloadbalancer-viewer-role
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: lbconfig-operator
    app.kubernetes.io/part-of: lbconfig-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalloadbalancer-viewer-role
rules:
  - apiGroups:
      - lb.lbconfig.carlosedp.com
    resources:
      - externalloadbalancers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - lb.lbconfig.carlosedp.com
    resources:
      - externalloadbalancers/status
    verbs:
      - get
