# permissions for end users to edit externalloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalloadbalancer-editor-role
rules:
- apiGroups:
  - lb.lbconfig.io
  resources:
  - externalloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.lbconfig.io
  resources:
  - externalloadbalancers/status
  verbs:
  - get
