# permissions for end users to view externalloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalloadbalancer-viewer-role
rules:
- apiGroups:
  - lb.lbconfig.io
  resources:
  - externalloadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.lbconfig.io
  resources:
  - externalloadbalancers/status
  verbs:
  - get
