# permissions for end users to view infraloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infraloadbalancer-viewer-role
rules:
- apiGroups:
  - lb.lbconfig.io
  resources:
  - infraloadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.lbconfig.io
  resources:
  - infraloadbalancers/status
  verbs:
  - get
