# permissions for end users to view loadbalancerbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancerbackend-viewer-role
rules:
- apiGroups:
  - lb.lbconfig.carlosedp.com
  resources:
  - loadbalancerbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.lbconfig.carlosedp.com
  resources:
  - loadbalancerbackends/status
  verbs:
  - get
