# permissions for end users to edit loadbalancerbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancerbackend-editor-role
rules:
- apiGroups:
  - lb.lbconfig.io
  resources:
  - loadbalancerbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.lbconfig.io
  resources:
  - loadbalancerbackends/status
  verbs:
  - get
