
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - lb.lbconfig.io
  resources:
  - infraloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.lbconfig.io
  resources:
  - infraloadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lb.lbconfig.io
  resources:
  - loadbalancerbackends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lb.lbconfig.io
  resources:
  - secrets
  verbs:
  - get
  - list
