apiVersion: lb.lbconfig.carlosedp.com/v1
kind: LoadBalancerBackend
metadata:
  name: backend-dummy-sample
  namespace: lbconfig-operator-system
spec:
  provider:
    vendor: dummy
    host: "1.2.3.4"
    port: 443
    creds: dummy-creds
    validatecerts: no
