# Create with commands below:
# kubectl create secret generic f5-creds --from-literal=username=admin --from-literal=password=admin123 --namespace lbconfig-operator-system
# or
# kubectl create secret generic netscaler-creds --from-literal=username=nsroot --from-literal=password=nsroot --namespace lbconfig-operator-system
apiVersion: v1
kind: Secret
metadata:
  name: f5-creds
  namespace: lbconfig-operator-system
data:
  password: YWRtaW4xMjM=
  username: YWRtaW4=
